### ISSUE TITLE
Basic CI/CD with docker

### ISSUE THREAD

**Issue by atz-dev** [Jobseer/Jobseer#1]
**Is your feature request related to a problem? Please describe.**
Test the project, dependencies and things before deployment

**Describe the solution you'd like**
CI/CD yaml files for github ci

**Describe alternatives you've considered**
external ci (ex: circle ci, gitlab ci, etc)

**Additional context**
Sprint 1 - Forward

**Comment by TheNsym** [comment]
CI/CD:
- Lancement d'une instance du projet via docker-compose
- Detecte si le projet est lancer et fonctionnel
   -  Lancement de l'app
   -  App accessible sur l'ip et le port associé
