### ISSUE TITLE
Job analysis - Data scientist

### ISSUE THREAD

**Issue by atz-dev** [Jobseer/Jobseer#13]
**Tasks :**

- [x] How they were created and why ?
- [x] Competences / studies needed for this job ?
- [x] What people who do these jobs did before ? Which competences were useful for this new job ?
- [x] How could we have predicted this job before it was created ?

**Comment by TheNsym** [comment]
-Création:
  - Fracture technologique, baisse du prix du stockage
-Compétences requises:
  - programmation (R, Python, C, C++, SQL…)
  - statistiques
  - machine learning
  - En algèbre linéaire et des fonctions de plusieurs variables
Métier similaire:
  - Statisticien/analyste, compétence similaire au data scientist nécéssitant une formation complémentaire en programmation et en machine learning

**Comment by TheNsym** [comment]
Le statisticien est un collecteur d’informations. Mathématicien expert en probabilités, il traite et analyse des données qu’il traduit en tableaux, en graphiques, en courbes, en histogrammes et en camemberts.

Formation statiticien:
 -minimum bac +2
Formation data scientist:
 - Un Bac + 4 ou Bac +5 en informatique, management, statistiques ou en marketing
