### ISSUE TITLE
Job analysis - Community manager

### ISSUE THREAD

**Issue by atz-dev** [Jobseer/Jobseer#16]
**Tasks :**

- [x] How they were created and why ?
- [x] Competences / studies needed for this job ?
- [x] What people who do these jobs did before ? Which competences were useful for this new job ?
- [x] How could we have predicted this job before it was created ?

**Comment by Baptiste-Roux** [comment]
**Comment c’est venu** :
Avec l'arrivée des réseaux sociaux, on a vu se développer des communautés autour de certaines personnes ou certaines entreprises. Les informations transmises par ces entreprises et ces personnes sont donc très largement diffusées et partagées par leur communauté. Il fallait donc toucher le plus grand nombre de personnes et donc pour cela savoir communiquer à un large spectre de personnes. Au début, les personnes qui s'y connaissaient le mieux étaient en charge de la communication via les réseaux, ce qui possiblement fait perdre du temps sur autre chose. C'est à partir de là qu'est né le métier de community manager. C'est une personne qui va, sans activité parallèle, gérer les différents réseaux et communautés du l'entreprise ou de la personne.

**Compétences** :

* Autonomie et réactivité
* Ecoute et curiosité
* Modérateur et diplomate 
* Stratège
* Bon communiquant et bon rédacteur
* Notions de graphisme / Design
* Culture web et connaissance du secteur de l'entreprise
* Compréhension des mécanismes communautaires
* Connaissance et maîtrise des différents réseaux sociaux
* Connaissance du SMO (Social Media Optimization) et des principales règles du référencement

Le métier de community manager est accessible à partir d'un BAC+2. Beaucoup de diplômes mènent à cela car les compétences sont présentes dans de nombreux cursus (communication, management, marketing digital, commerce, sciences humaines).

**Que faisaient les influenceurs avant d’être influenceurs** :
Les personnes déjà sur le marché du travail lorsque le métier de community manager est arrivé étaient pour la plus part dans la communication. On retrouve par exemple des commerciaux ou des journalistes.

**Comment-auraient on pu prévoir l’arrivée du métier d’influenceur** :
Pour prévoir ce métier, il aurait anticiper l'ampleur des communautés créées suite à l'apparition des réseaux sociaux. En voyant cela il aurait été facile d'en déduire le besoin de communication avec celles-ci.

**Application des recherches pour le prédire futur**
Avec ce que nous venons de voir, nous pouvons imaginer d'auutres métiers. On peut par exemple réfléchir aux applications de l'IA dans le monde de la communication et donc prédire le métier de Administrateur de robot Community Manager qui serait en charge de gérer des IA pour plusieurs entreprises.
