### ISSUE TITLE
Basic containerization of apps

### ISSUE THREAD

**Issue by atz-dev** [Jobseer/Jobseer#7]
**Is your feature request related to a problem? Please describe.**
Scalability

**Describe the solution you'd like**
Containerization of every components of the app in Docker w/ Docker-compose

**Describe alternatives you've considered**
There isn't any alternative to consider

**Additional context**
This task is among a largest one who's aim to dockerize and make a kube cluster

**Comment by TheNsym** [comment]
App sous docker et lancé via docker compose
