### ISSUE TITLE
Job analysis - Influencer

### ISSUE THREAD

**Issue by atz-dev** [Jobseer/Jobseer#8]
**Tasks :**

- [x] How they were created and why ?
- [x] Competences / studies needed for this job ?
- [x] What people who do these jobs did before ? Which competences were useful for this new job ?
- [x] How could we have predicted this job before it was created ?

**Comment by Baptiste-Roux** [comment]
**Comment c’est venu** :
Avec l’arrivée d’internet, les blogs ont vu le jour. Certains sont devenus tellement  populaires que de grosses communautés se sont formées. Avec l’arrivée des réseaux sociaux c’est une certaines proximité qui s'installe entre le blogueur et sa communauté. Ces personnes dont la passion est de partager sur les réseaux ont beaucoup d’influence. Si bien que certaines entreprises paient pour avoir de la promotion de produits au travers des influenceurs. Cette pratique s’est répandue sur tous les réseaux et certains blogueurs influants, voyant l’argent qu’ils pouvaient gagner grâce à cette activité ont quitté leur travail pour se lancer pleinement dans leur activité Instagram/Youtube/Autre. De là est né le métier d’influenceur, utile pour les entreprises qui veulent de la visibilité.

**Compétences** :

- Connaissance et maîtrise des principaux réseaux sociaux
- Capacité d'écriture créative, content creation, copywriting et storytelling
- Connaissance des stratégies pour augmenter la visibilité, les followers et l'engagement de ses profils
- Capacité de travailler en réseau et de communiquer avec les followers, entreprises, bloggeurs et autres influenceurs
- Compétences dans l'utilisation des instruments de communication visuelle et multimédia
- Capacités analytiques et d'interprétation des données
- Compétences en organisation et planification
- Créativité et charisme
- Forte personnalité

Il n’y a pas d'études particulières pour le moment même si des études en communications et marketing aident grandement.

**Que faisaient les influenceurs avant d’être influenceurs** :
La plupart des influenceurs mainstream ont toujours été influenceurs comme Squeezie, Pewdiepie cependant on retrouve des catégorie d’influenceurs ciblés qui proviennent d’une branche spécifique. On peut prendre l’exemple d’Axolot qui, avant de raconter des histoires sur youtube, racontait des histoires à la radio. Prenons aussi l’exemple de Dr k de la chaine Healthy Gamer, psychologue avant de créer une chaine youtube et twitch où il parle aux gamers de santé mentale. Les compétences ‘métier’ qu’ils avaient ont été mises à disposition pour leur nouvelle activité

**Comment-auraient on pu prévoir l’arrivée du métier d’influenceur** :
Pour prévoir ce métier, il aurait fallu réfléchir à toutes les utilisations possibles des blogs et des réseaux sociaux avant même qu’ils émergent (étant donné que les influenceurs sont arrivés en meme temps que les réseaux sociaux). Le fait qu’internet permette de communiquer avec le monde entier démocratise le capitalisme à grande échelle à travers les influenceurs.

**Comment by atz-dev** [comment]
Hésite pas à utiliser le "Close with comment" comme ça le ticket est fermé, et ça passe automatiquement en "Done" sur le board
