### ISSUE TITLE
Job analysis - Big data architect

### ISSUE THREAD

**Issue by atz-dev** [Jobseer/Jobseer#9]
**Tasks :**

- [x] How they were created and why ?
- [x] Competences / studies needed for this job ?
- [x] What people who do these jobs did before ? Which competences were useful for this new job ?
- [x] How could we have predicted this job before it was created ?

**Comment by TheNsym** [comment]
-Création:

- Fracture technologique, baisse du prix du stockage

-Compétences requises:

- programmation (R, Python, C, C++, SQL…)
- machine learning
- infrastructure serveur

-Métier lié:

- administrateur système ayant suivi une formation en data analysis
- statisticien ayant une formation en administration système

**Comment by TheNsym** [comment]
C’est la personne qui se charge de collecter des données brutes pour l’entreprise.
Après avoir collecté les données brutes, l’architecte Big Data se charge de créer et d’optimiser des infrastructures de stockage, manipulation et restitution. Il doit élaborer une architecture de Data Management et concevoir un plan pour intégrer, centraliser, protéger et maintenir les données. 

-Formation statiticien:
minimum bac +2

-Formation administrateur système:
Bac+2 à Bac+5 dans une université, une école d’informatique ou d’ingénieur.

-Formation data scientist:
Un Bac + 4 ou Bac +5 en informatique, management, statistiques ou en marketing
